# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/EndAlignment:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Style/StringLiterals:
  Enabled: false
