# docker-compose.yml

version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY}
      RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: ${DB_HOST}
      DB_URL: ${DB_URL:-DB_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_DATABASE}}
      RACK_ENV: ${RACK_ENV}
      RAILS_ENV: ${RAILS_ENV}
      DOCKERIZED: ${DOCKERIZED}
      SERVER_MODE: ${SERVER_MODE}
      RAILS_SERVE_STATIC_FILES: ${RAILS_SERVE_STATIC_FILES}

    ports:
      - 3000:3000
      - "${SSH_PORT:+${SSH_PORT}:${SSH_PORT}}"

    volumes:
      - ./log:/rails/log
      - ./tmp:/rails/tmp
      - storage:/rails/storage
      - user_home:/home/paul
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Newhall2Eastsound!}

    ports:
      - "5432:5432"
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - app-network

volumes:
  postgres_data:
  storage:
  user_home:

networks:
  app-network:
