# docker-compose-db.yml

version: "3.9"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-DB

    image: paul-carrick-db
    container_name: paul-carrick-db

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${EXTERNAL_PORT}:${INTERNAL_PORT}"
      - "${SSH_PORT:+${SSH_PORT}:${SSH_PORT}}"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
