# DockerFile-DB

# Use the official PostgreSQL image as the base
FROM postgres:15

# Set environment variables for PostgreSQL configuration
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV POSTGRES_DB=rails_db

EXPOSE 5432 5433

# Define a volume for persistent data storage
VOLUME /var/lib/postgresql/data

COPY initdb.d/ /docker-entrypoint-initdb.d/

# Default command (inherited from the base image)
CMD ["postgres"]
