# /app/controllers/admin/menu_items

class Admin::SiteSetupsController < Admin::AbstractAdminController
  def initialize
    super

    @page_limit     = 20
    @default_column = 'configuration_name'
    @has_query      = false
    @has_sort       = true
    @model_class    = SiteSetup
  end

  COLOR_ARRAY = [
    %w[ Default #0d6efd ],
    %w[ Black black ],
    %w[ White white ],
    %w[ Red red ],
    %w[ Green green ],
    %w[ Blue blue ],
    %w[ Gray gray ],
    %w[ Yellow yellow ],
    %w[ Cyan cyan ],
    %w[ Magenta magenta ],
    %w[ Lime lime ],
    %w[ Silver silver ],
    %w[ Maroon maroon ],
    %w[ Olive olive ],
    %w[ Green green ],
    %w[ Purple purple ],
    %w[ Teal teal ],
    %w[ Navy navy ],
    %w[ Orange orange ],
    %w[ Gainsboro Gainsboro ],
    %w[ "Light Gray" LightGray ],
    %w[ "Dark Gray" DarkGray ],
    %w[ "Dim Gray" DimGray ],
    %w[ "Slate Gray" SlateGray ],
    %w[ "Light Slate Gray" LightSlateGray ],
    %w[ "Dark Slate Gray" DarkSlateGray ],
    %w[ "White Smoke" WhiteSmoke ],
    %w[ "Light Coral" LightCoral ],
    %w[ "Indian Red" IndianRed ],
    %w[ "Crimson" Crimson ],
    %w[ "Fire Brick" FireBrick ],
    %w[ "Dark Red" DarkRed ],
    %w[ "Pink" Pink ],
    %w[ "Light Pink" LightPink ],
    %w[ "Hot Pink" HotPink ],
    %w[ "Deep Pink" DeepPink ],
    %w[ "Medium Violet Red" MediumVioletRed ],
    %w[ "Pale Violet Red" PaleVioletRed ],
    %w[ "Coral" Coral ],
    %w[ "Tomato" Tomato ],
    %w[ "Orange Red" OrangeRed ],
    %w[ "Dark Orange" DarkOrange ],
    %w[ "Orange" Orange ],
    %w[ "Moccasin" Moccasin ],
    %w[ "Peach Puff" PeachPuff ],
    %w[ "Papaya Whip" PapayaWhip ],
    %w[ "Saddle Brown" SaddleBrown ],
    %w[ "Sienna" Sienna ],
    %w[ "Chocolate" Chocolate ],
    %w[ "Peru" Peru ],
    %w[ "Tan" Tan ],
    %w[ "Burly Wood" BurlyWood ],
    %w[ "Wheat" Wheat ],
    %w[ "Gold" Gold ],
    %w[ "Yellow" Yellow ],
    %w[ "Light Yellow" LightYellow ],
    %w[ "Lemon Chiffon" LemonChiffon ],
    %w[ "Khaki" Khaki ],
    %w[ "Pale Golden Rod" PaleGoldenRod ],
    %w[ "Dark Khaki" DarkKhaki ],
    %w[ "Lawn Green" LawnGreen ],
    %w[ "Chartreuse" Chartreuse ],
    %w[ "Green Yellow" GreenYellow ],
    %w[ "Lime Green" LimeGreen ],
    %w[ "Pale Green" PaleGreen ],
    %w[ "Light Green" LightGreen ],
    %w[ "Medium Spring Green" MediumSpringGreen ],
    %w[ "Spring Green" SpringGreen ],
    %w[ "Forest Green" ForestGreen ],
    %w[ "Sea Green" SeaGreen ],
    %w[ "Medium Sea Green" MediumSeaGreen ],
    %w[ "Dark Sea Green" DarkSeaGreen ],
    %w[ "Olive Drab" OliveDrab ],
    %w[ "Dark Olive Green" DarkOliveGreen ],
    %w[ "Dark Green" DarkGreen ],
    %w[ "Light Cyan" LightCyan ],
    %w[ "Pale Turquoise" PaleTurquoise ],
    %w[ "Aquamarine" Aquamarine ],
    %w[ "Medium Aquamarine" MediumAquamarine ],
    %w[ "Turquoise" Turquoise ],
    %w[ "Medium Turquoise" MediumTurquoise ],
    %w[ "Dark Turquoise" DarkTurquoise ],
    %w[ "Light Sea Green" LightSeaGreen ],
    %w[ "Cadet Blue" CadetBlue ],
    %w[ "Dark Cyan" DarkCyan ],
    %w[ "Light Blue" LightBlue ],
    %w[ "Powder Blue" PowderBlue ],
    %w[ "Sky Blue" SkyBlue ],
    %w[ "Light Sky Blue" LightSkyBlue ],
    %w[ "Deep Sky Blue" DeepSkyBlue ],
    %w[ "Dodger Blue" DodgerBlue ],
    %w[ "Cornflower Blue" CornflowerBlue ],
    %w[ "Royal Blue" RoyalBlue ],
    %w[ "Medium Blue" MediumBlue ],
    %w[ "Dark Blue" DarkBlue ],
    %w[ "Midnight Blue" MidnightBlue ],
    %w[ "Lavender" Lavender ],
    %w[ "Thistle" Thistle ],
    %w[ "Plum" Plum ],
    %w[ "Violet" Violet ],
    %w[ "Orchid" Orchid ],
    %w[ "Medium Orchid" MediumOrchid ],
    %w[ "Dark Orchid" DarkOrchid ],
    %w[ "Dark Violet" DarkViolet ],
    %w[ "Blue Violet" BlueViolet ],
    %w[ "Medium Purple" MediumPurple ],
    %w[ "Slate Blue" SlateBlue ],
    %w[ "Medium Slate Blue" MediumSlateBlue ],
    %w[ "Dark Slate Blue" DarkSlateBlue ],
    %w[ "Snow" Snow ],
    %w[ "Honey Dew" HoneyDew ],
    %w[ "Mint Cream" MintCream ],
    %w[ "Azure" Azure ],
    %w[ "Alice Blue" AliceBlue ],
    %w[ "Ghost White" GhostWhite ],
    %w[ "Floral White" FloralWhite ],
    %w[ "Old Lace" OldLace ],
    %w[ "Ivory" Ivory ],
    %w[ "Seashell" Seashell ],
    %w[ "Beige" Beige ],
    %w[ "Linen" Linen ],
    %w[ "Antique White" AntiqueWhite ],
    %w[ "Dark Slate Gray" DarkSlateGray ],
    %w[ "Dim Gray" DimGray ],
    %w[ "Slate Gray" SlateGray ]
  ]
end
